### ISSUE TITLE
Need FAQ section update

### ISSUE THREAD

**Issue by prineth** [IEEE-Student-Branch-NSBM/Duothan3.0-Website#19]
add FAQ content here 
![image](https://user-images.githubusercontent.com/70090385/216294387-0c57bbd0-f667-4986-8f30-162291c3375c.png)

[https://docs.google.com/file/d/16iC7HeKwsjngTDUMbRrhxPDihnq5NYNF/edit?usp=docslist_api&filetype=msword](url)

**Comment by lokeshvasnik** [comment]
What you want to do exactly

**Comment by Arun-cn** [comment]
faq content have multiple answer with bullet points.

**Comment by prineth** [comment]
Great work @Arun-cn 🖤
